#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/github.com ~/dev -mindepth 1 -type d -exec test -e '{}/.git' ';' -print -prune | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

cd $selected
tmux
